services:
  - type: web
    name: greenhouse-system
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: RASPI_API_KEY
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: greenhouse-system
          property: host
